---
- name: Vultr up | Create VM
  local_action:
    module: vr_server
    state: present
    name: "{{ inventory_hostname }}"
    os: "{{ vultr_os }}"
    plan: "{{ vultr_plan }}"
    region: "{{ vultr_region }}"
    auto_backup_enabled: no
    private_network_enabled: yes
    ssh_key: "{{ vultr_key }}"
  register: response
  until: response is success
  retries: 3
  delay: 10

- name: Vultr up | Setup ssh host
  set_fact:
    ansible_host: "{{ response.vultr_server.v4_main_ip }}"
    private_ip: "{{ response.vultr_server.internal_ip }}"
    vm_info: "{{ response.vultr_server }}"

- name: Vultr up | Wait for ready
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: 22
    delay: 5

  # Run initialize tasks only when vm has created
- block:
  - debug: msg="{{ vm_info }}"

    # Python is required to continue running tasks.
  - import_tasks: python.yml

  - name: Vultr up | Setup hostname
    raw: hostnamectl set-hostname "{{ inventory_hostname }}"

  - name: Vultr up | gathering facts
    setup:

  - name: Vultr up | Put key
    copy:
      src: "{{ vultr_key_path }}"
      dest: "{{ remote_sshkey_file_path }}"
      owner: root
      group: root
      mode: 0600

  - import_tasks: private_ip.yml

  when: response.changed

